export default {
  names: ['stranger'],
  greetings: [
    'Greetings, {title}!',
    'What is thy bidding, {title}?',
    'Yes, {title}?',
    'Welcome, {title}!',
    'Ah, {title}!',
    'Salutations, {title}!',
    'Hello, {title}.',
    "What's up, {title}?",
    '{title}! How may I be of assistance?',
    'What is your command, {title}?',
  ],
  nobleModifiers: {
    all: ['citizen', 'comrade', 'supreme', 'my', 'grand'],
    male: ['lord'],
    female: ['lady'],
  },
  titles: {
    nobleMale: [
      'sir {name}',
      '{modifier} master {name}',
      '{modifier} king {name}',
      '{modifier} emperor {name}',
      '{modifier} emperor {name}',
      '{modifier} duke {name}',
      '{modifier} earl {name}',
      '{modifier} count {name}',
      '{modifier} viscount {name}',
    ],
    nobleFemale: [
      'dame {name}',
      '{modifier} mistress {name}',
      '{modifier} queen {name}',
      'lady',
      '{modifier} empress {name}',
      '{modifier} empress {name}',
      '{modifier} dutchess',
      '{modifier} countess',
      '{modifier} viscountess',
    ],
    noble: [
      'ser {name}',
      '{name}-sama',
      '{name}-sensi',
      '{name}-senpai',
      '{modifier} thane',
      'your majesty',
      'your grace',
      'lord admiral {name}',
      'your excellency',
      'king {name}, first of your name',
      'caesar',
      '{modifier} consul',
      '{modifier} magister',
      '{modifier} sultan',
      '{modifier} vizier',
    ],
    commonerMale: ['my man', 'guy', 'dude'],
    commonerFemale: [],
    commoner: [
      '{name}',
      '{name}-san',
      '{name}-chan',
      '{name}-kun',
      'friend',
      'buddy',
      'pal',
      'citizen',
      'my dear {name}',
      'bub',
    ],
  },
};
